#!/bin/bash
#$ -l h_vmem=8g,h_rt=144:00:00

export LD_LIBRARY_PATH=/home/lvapeab/smt/software/tcl/lib
srilmpath=/home/lvapeab/smt/software/srilm/bin/i686
rnnpath=/home/lvapeab/smt/software/rnnlm-0.4b

trainfile=/home/lvapeab/smt/tasks/ue/esen/DATA/training.en
validfile=/home/lvapeab/smt/tasks/xerox/enes/DATA/dev.en
destdir=/home/lvapeab/RNNLMs/ue





mkdir -p $destdir




class_size=200
bptt_steps=7
hidden_size=600
#	    for bptt_block in 10 20 
	

#	    do 


################################
# TRAINING OF RNNLM
################################

		$rnnpath/rnnlm -train $trainfile -valid $validfile -rnnlm $destdir"/lm-n"$hidden_size"c"$class_size"bp"$bptt_steps"bl"$bptt_block".mod" -hidden $hidden_size -debug 2 -class $class_size -bptt $bptt_steps -bptt-block 10 -direct-order 5
