#!/bin/bash
#$ -l h_rt=144:00:00
#$ -l h_vmem=12g
export LD_LIBRARY_PATH=/home/lvapeab/smt/software/tcl/lib
srilmpath=/home/lvapeab/smt/software/srilm/bin/i686
rnnpath=/home/lvapeab/smt/software/rnnlm-0.4b

trainfile=/home/lvapeab/smt/tasks/europarl/enes/DATA/europarl.truecased.1.es.cleaned.trunc40
validfile=/home/lvapeab/smt/tasks/europarl/enes/DATA/newstest2012.tc.es
destdir=/home/lvapeab/RNNLMs/Europarl

mkdir $destdir

 for class_size in 400
    do
  for  bptt_steps in 20
	do
	for hidden_size in 400
	do
#	    for bptt_block in 10 20 
	

#	    do 


################################
# TRAINING OF RNNLM
################################

		$rnnpath/rnnlm -train $trainfile -valid $validfile -rnnlm $destdir"/lm-n"$hidden_size"c"$class_size"bptt"$bptt_steps".mod" -hidden $hidden_size -debug 2 -class $class_size -bptt $bptt_steps

	done
    done
done