#!/bin/bash

SRILM_DIR=/home/alvaro/smt/software/srilm/bin/i686-m64


AWK=/usr/bin/awk
SORT=/usr/bin/sort
PYTHON=/usr/bin/python
sortpars="-S 131072"
sortT="yes"
sortm="yes"
SPLIT=/usr/bin/split
SED=/bin/sed
GREP=/bin/grep
SED=/bin/sed
UNIQ=/usr/bin/uniq
BASENAME=/usr/bin/basename
SSH=/usr/bin/ssh
HEAD=/usr/bin/head
TAIL=/usr/bin/tail
MKTEMP=/bin/mktemp


usage(){
    echo "Usage: merge_models -main <trans1> -backoff <trans2> [-max_unk <int>] [-unk_sym <string>] [-tmpdir <dir>] [-out <output>] [-v] [-t <string>] [-lm <string>] [-order <int>]"
    echo " -main <string>       : File with sentences generated by the main TM."
    echo " -backoff <string>    : File with sentences generated by the secondary TM"
    echo " -max_unk <int>         : Number of unknown words per sentence allowed in the main translation file."
    echo " -unk_sym <string>    : Unknown word symbol (default UNK)."
    echo " -tmpdir <string>     : Temporal directory (default current directory)."
    echo " -out <string>        : Output file (default, standard output)."
    echo " -v                   : Verbose mode."
    echo " -t <string>          : Technique to select the translations. One of: \"unk\", \"ppl\", \"combined\" (default \"unk\")."
    echo " -lm <string>         : Language model for computing perplexities."
    echo " -order <int>         : Order of the language model (default 4)."
}


str_is_option()
{
    echo "" | ${AWK} -v s=$1 '{if(!match(s,"-[a-zA-Z]")) print "0"; else print "1"}'
}


main=""
tmpdir="./"
main_given=0
backoff=""
backoff_given=0
max_unk=""
max_unk_given=0
unk_sym="UNK"
lm_given=0
technique="unk"
order=4

output="1"


while [ $# -ne 0 ]; do
 case $1 in
     "--help") usage
         exit 0
         ;;
     "-tdir") shift
         if [ $# -ne 0 ]; then
             tmpdir=$1
         else
             tmpdir="./"
         fi
         ;;


     "-main") shift
         if [ $# -ne 0 ]; then
             main=$1
	     main_given=1
         else
             main_given=0
         fi
         ;;
     "-backoff") shift
         if [ $# -ne 0 ]; then
             backoff=$1
	     backoff_given=1
         else
             backoff_given=0
         fi
         ;;
     
     "-max_unk") shift
         if [ $# -ne 0 ]; then
             max_unk=$1
	     max_unk_given=1
         else
             max_unk_given=0
         fi
         ;;

     "-unk_sym") shift
         if [ $# -ne 0 ]; then
             unk_sym=$1
	     
         fi
         ;;

     "-out") shift
         if [ $# -ne 0 ]; then
             output=$1
         else
             tmpdir="1"
         fi
         ;;


     "-t") shift
         if [ $# -ne 0 ]; then
             technique=$1
         else
             technique="unk"
         fi
         ;;


     "-lm") shift
         if [ $# -ne 0 ]; then
             lm=$1
	     lm_given=1
         else
             lm_given=0
         fi
         ;;


     "-order") shift
         if [ $# -ne 0 ]; then
             order=$1
	     
         else
             order=4
         fi
         ;;

     "-v") verbose_opt="-v"
         ;;

    esac
    shift
done

#### Verify parameters                                                                                                                        


if [ ${main_given} -eq 0 ]; then
    # invalid parameters                                                                                                                      
    echo "Error: -main option not given"
    exit 1
fi
if [ ${backoff_given} -eq 0 ]; then
    # invalid parameters                                                                                                                      
    echo "Error: -backoff option not given"
    exit 1
fi
#Parameters are OK         



mkdir -p $tmpdir


### Script selection


if [ "${technique}" == "unk"  ]; then

    if [ ${max_unk_given} -eq 0 ]; then
    # invalid parameters                                                                                                      
	echo "Error: -max_unk option not given"
	exit 1
    fi
    MERGE_SCRIPT=/home/alvaro/smt/software/scripts/tm_combination/combine_tm_unk.py
    cat $main  | awk -v unk=$unk_sym '{counter=0; 
                                  for(i=1;i<=NF;i++){
                                      if($i == unk) 
                                          counter++;
                                  }
                                  print counter}' > ${tmpdir}/unk_count
    $PYTHON $MERGE_SCRIPT  $main $backoff ${tmpdir}/unk_count $max_unk $verbose_opt >& $output

    exit 1
fi




if [ "${technique}" == "ppl"  ]; then

    if [ ${lm_given} -eq 0 ]; then
    	echo "Error: -lm option not given"
	exit 1
    fi
    MERGE_SCRIPT=/home/alvaro/smt/software/scripts/tm_combination/combine_tm_ppl.py   
    $SRILM_DIR/ngram -ppl $main -order $order -lm $lm -debug 1 |grep logprob |awk '{print $4}' > ${tmpdir}/nmt.probs
    $SRILM_DIR/ngram -ppl $backoff -order $order -lm $lm -debug 1 |grep logprob |awk '{print $4}' > ${tmpdir}/pbmt.probs
    $PYTHON $MERGE_SCRIPT  $main $backoff ${tmpdir}/nmt.probs ${tmpdir}/pbmt.probs $verbose_opt >& $output
    exit 1
fi



if [ "${technique}" == "combined"  ]; then

    if [ ${lm_given} -eq 0 ]; then
    	echo "Error: -lm option not given"
	exit 1
    fi
    MERGE_SCRIPT=/home/alvaro/smt/software/scripts/tm_combination/combine_tm_pplUnk.py

    
    cat $main  | awk -v unk=$unk_sym '{counter=0; 
                                  for(i=1;i<=NF;i++){
                                      if($i == unk) 
                                          counter++;
                                  }
                                  print counter}' > ${tmpdir}/unk_count
    $SRILM_DIR/ngram -ppl $main -order $order -lm $lm -debug 1 |grep logprob |awk '{print $4}' > ${tmpdir}/nmt.probs
    $SRILM_DIR/ngram -ppl $backoff -order $order -lm $lm -debug 1 |grep logprob |awk '{print $4}' > ${tmpdir}/pbmt.probs

    $PYTHON $MERGE_SCRIPT  $main $backoff ${tmpdir}/nmt.probs ${tmpdir}/pbmt.probs ${tmpdir}/unk_count $max_unk $verbose_opt >& $output
    exit 1
fi

